name: Add commit to the commit file
run-name: Print When Push
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.actor }} has made a push to the repo !"
